from sqlmodel import Field, SQLModel, Index
from datetime import datetime

# Id's could be None, beacuse they will be generated by the database

class Client(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    phone_number: str = Field(unique=True)
    name: str | None = None

class Service(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    price: float 
    name: str
    duration_minutes: int

'''
Appointment class has a composite index because in services/appointment_service the check_availability method
would be doing searches with them, and a barbershop won't have thousands of inserts daily, so it is really
cost-effective architectural decision
'''
class Appointment(SQLModel, table=True):
    __tablename__ = "appointment"
    __tableargs__ = (
        Index("ix_appointment_dates", "start_datetime", "end_datetime")
    )
    id: int | None = Field(default=None, primary_key=True)
    google_calendar_id: str | None = None
    client_id: int = Field(foreign_key="client.id")
    start_time: datetime
    end_time: datetime

class ServiceAppointment(SQLModel, table=True):
    appointment_id: int = Field(foreign_key="appointment.id", primary_key=True)
    service_id: int = Field(foreign_key="service.id", primary_key=True)

'''
Some business should have woker class, that businness are the ones that have +2 workers.
The reason is what happens when checking availabity at one hour, if we don't filter by barber
'''