from sqlmodel import Field, SQLModel
from datetime import datetime

# Id's could be None, beacuse they will be generated by the database

class Client(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    phone_number: str = Field(unique=True)
    name: str | None = None

class Service(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    price: float 
    name: str
    duration_minutes: int

class Appointment(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    google_calendar_id: str | None = None
    client_id: int = Field(foreign_key="client.id")
    start_time: datetime
    end_time: datetime

class ServiceAppointment(SQLModel, table=True):
    appointment_id: int = Field(foreign_key="appointment.id", primary_key=True)
    service_id: int = Field(foreign_key="service.id", primary_key=True)